name: Release

on: 
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.draft_release.outputs.id }}
      html_url: ${{ steps.draft_release.outputs.html_url }}
      upload_url: ${{ steps.draft_release.outputs.upload_url }}
    steps:
      - name: Draft release
        id: draft_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true

  build_release: 
    name: Build release
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload metadata
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./plugins.json
          asset_name: plugins.json
          asset_content_type: application/json

      - name: Upload audio preview
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ github.event.repository.name }}.flac
          asset_name: ${{ github.event.repository.name }}.flac
          asset_content_type: audio/flac

      - name: Upload image preview
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ github.event.repository.name }}.jpg
          asset_name: ${{ github.event.repository.name }}.jpg
          asset_content_type: image/jpeg

      - name: Compress lossless version
        run: zip -r ./${{ github.event.repository.name }}.zip *

      - name: Upload lossless version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip

      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1

      - name: Create lossy version
        run: |
          for i in ./Samples/*.flac; do ffmpeg -i "$i" -b:a 128k "${i%.*}.ogg"; done
          sed -i 's/flac/ogg/g' 'Salamander Grand Piano V3.sfz'
          find . -name "*.flac" -type f -delete
          rm salamander-grand-piano.zip

      - name: Compress lossy version
        run: zip -r ./${{ github.event.repository.name }}-lossy.zip *

      - name: Upload lossy version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ github.event.repository.name }}-lossy.zip
          asset_name: ${{ github.event.repository.name }}-lossy.zip
          asset_content_type: application/zip

      - name: Publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.create_release.outputs.id }}
